export const hofMember = [
{
  firstName: "Hank",
  lastName: "Aaron",
  teams: ["Milwaukee Braves", "Atlanta Braves", "Milwaukee Brewers"],
  primaryTeam: ["Atlanta Braves"],
  position: "Right Fielder",
  nationality: "American",
  race: "African American",
  yearsActive: "1954–1976",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "25× All-Star",
    "1957 NL MVP",
    "3× Gold Glove",
    "World Series Champion (1957)",
    "755 career home runs"
  ],
  birthDay: "2/5/1934",
  deathDay: "1/22/2021",
  realName: "Henry Louis Aaron",
  nickNames: "Hammerin' Hank",
  yearInducted: 1982,
  commentOne: "Broke Babe Ruth’s all-time home run record with 755.",
  commentTwo: "One of the greatest hitters and respected figures in baseball history.",
},

{
  firstName: "Grover Cleveland",
  lastName: "Alexander",
  teams: ["Philadelphia Phillies", "Chicago Cubs", "St. Louis Cardinals"],
  primaryTeam: ["Philadelphia Phillies"],
  position: "Pitcher",
  nationality: "American",
  race: null,
  yearsActive: "1911–1930",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "3× Triple Crown",
    "6× NL Wins Leader",
    "6× NL ERA Leader",
    "World Series Champion (1926)"
  ],
  birthDay: "2/26/1887",
  deathDay: "11/4/1950",
  realName: "Grover Cleveland Alexander",
  nickNames: "Old Pete",
  yearInducted: 1938,
  commentOne: "One of the greatest pitchers in MLB history with 373 career wins.",
  commentTwo: "Pitched crucial relief in 1926 World Series Game 7 for Cardinals.",
},

{
  firstName: "Dick",
  lastName: "Allen",
  teams: ["Philadelphia Phillies", "Chicago White Sox", "St. Louis Cardinals", "Los Angeles Dodgers", "Oakland Athletics"],
  primaryTeam: ["Philadelphia Phillies"],
  position: "First Baseman / Third Baseman",
  nationality: "American",
  race: "African American",
  yearsActive: "1963–1977",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "7× All-Star",
    "1972 AL MVP",
    "1964 NL Rookie of the Year",
    "2× AL Home Run Leader"
  ],
  birthDay: "3/8/1942",
  deathDay: "12/7/2020",
  realName: "Richard Anthony Allen",
  nickNames: "Wampum Walloper, Crash",
  yearInducted: null,  // Not yet officially inducted but often discussed as deserving
  commentOne: "One of the most feared sluggers of the 1960s and 70s.",
  commentTwo: "Known for hitting towering home runs and his complex relationship with the press.",
},

{
  firstName: "Roberto",
  lastName: "Alomar Jr.",
  teams: ["San Diego Padres", "Toronto Blue Jays", "Baltimore Orioles", "Cleveland Indians", "New York Mets", "Chicago White Sox", "Arizona Diamondbacks"],
  primaryTeam: ["Toronto Blue Jays"],
  position: "Second Baseman",
  nationality: "Puerto Rican",
  race: "Latino",
  yearsActive: "1988–2004",
  batHand: ["Switch"],
  throwHand: ["Right"],
  awards: [
    "12× All-Star",
    "10× Gold Glove",
    "4× Silver Slugger",
    "2× World Series Champion (1992, 1993)",
    "1992 ALCS MVP"
  ],
  birthDay: "2/5/1968",
  deathDay: null,
  realName: "Roberto Alomar Velázquez",
  nickNames: "Robbie",
  yearInducted: 2011,
  commentOne: "One of the greatest second basemen in MLB history.",
  commentTwo: "Key figure in the Toronto Blue Jays' back-to-back championships.",
},

  {
    firstName: "Walter",
    lastName: "Alston",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Sparky",
    lastName: "Anderson",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Cap",
    lastName: "Anson",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Luis",
    lastName: "Aparicio",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Luke",
    lastName: "Appling",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Richie",
    lastName: "Ashburn",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Earl",
    lastName: "Averill",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Jeff",
    lastName: "Bagwell",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Harold",
    lastName: "Baines",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Frank",
    lastName: "Baker",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Dave",
    lastName: "Bancroft",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Ernie",
    lastName: "Banks",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Al",
    lastName: "Barlick",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Ed",
    lastName: "Barrow",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Jake",
    lastName: "Beckley",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "CoolPapa",
    lastName: "Bell",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Adrian",
    lastName: "Beltré",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Johnny",
    lastName: "Bench",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Charles (Chief Bender)",
    lastName: "Bender",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Yogi",
    lastName: "Berra",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Craig",
    lastName: "Biggio",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Bert",
    lastName: "Blyleven",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Wade",
    lastName: "Boggs",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Jim",
    lastName: "Bottomley",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Lou",
    lastName: "Boudreau",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },
  {
    firstName: "Roger",
    lastName: "Bresnahan",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },
  {
    firstName: "George",
    lastName: "Brett",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },
  {
    firstName: "Lou",
    lastName: "Brock",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Dan",
    lastName: "Brouthers",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Mordecai",
    lastName: "Brown",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Ray",
    lastName: "Brown",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },


  {
    firstName: "Willard",
    lastName: "Brown",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },

  {
    firstName: "Morgan",
    lastName: "Bulkeley",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },
  
  {
    firstName: "Jim",
    lastName: "Bunning",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },
  
  {
    firstName: "Jesse",
    lastName: "Burkett",
    teams: [],
    primaryTeam: [],
    position: null,
    nationality: null,
    race: null,
    yearsActive: null,
    batHand: [],
    throwHand: [],
    awards: [],
    birthDay: null,
    deathDay: null,
    realName: null,
    nickNames: null,
    yearInducted: null,
    commentOne: null,
    commentTwo: null,
  },
  
  
  

























  {
    firstName: "Ken",
    lastName: "Griffey Jr.",
    teams: ["Seattle Mariners", "Cincinnati Reds", "Chicago White Sox"],
    primaryTeam: ["Seattle Mariners"],
    position: "Center Fielder",
    nationality: "American",
    race: null,
    yearsActive: "1989–2010",
    batHand: ["Left"],
    throwHand: ["Left"],
    awards: [
      "13× All-Star",
      "10× Gold Glove",
      "7× Silver Slugger",
      "1997 AL MVP",
    ],
    birthDay: "11/21/1969",
    deathDay: null,
    realName: "George Kenneth Griffey Jr.",
    nickNames: "The Kid, Junior",
    yearInducted: 2016,
    commentOne: "One of the most iconic swings in baseball history.",
    commentTwo: "Hit 630 career home runs.",
  },

  {
    firstName: "Ted",
    lastName: "Lyons",
    teams: ["Chicago White Sox"],
    primaryTeam: ["Chicago White Sox"],
    position: "Pitcher",
    nationality: "American",
    race: null,
    yearsActive: "1923–1946",
    batHand: ["Right"],
    throwHand: ["Right"],
    awards: ["All-Star (1939)", "ERA leader 3×"],
    birthDay: "12/28/1900",
    deathDay: "7/25/1986",
    realName: "Theodore Amar Lyons",
    nickNames: "Sunday Teddy",
    yearInducted: 1955,
    commentOne: "Pitched his entire career for the White Sox.",
    commentTwo: "Won 260 games with a 3.67 ERA.",
  },
  
  {
    firstName: "Willie",
    lastName: "Mays",
    teams: ["New York Giants", "San Francisco Giants", "New York Mets"],
    primaryTeam: ["San Francisco Giants"],
    position: "Center Fielder",
    nationality: "American",
    race: null,
    yearsActive: "1951–1973",
    batHand: ["Right"],
    throwHand: ["Right"],
    awards: [
      "24× All-Star",
      "2× NL MVP",
      "12× Gold Glove",
      "World Series Champion (1954)",
    ],
    birthDay: "5/6/1931",
    deathDay: "6/18/2024",
    realName: "Willie Howard Mays Jr.",
    nickNames: "The Say Hey Kid",
    yearInducted: 1979,
    commentOne: "Arguably the most complete player in MLB history.",
    commentTwo:
      "Famous for his over-the-shoulder catch in the 1954 World Series.",
  },
  
  {
    firstName: "Babe",
    lastName: "Ruth",
    teams: ["Boston Red Sox", "New York Yankees", "Boston Braves"],
    primaryTeam: ["New York Yankees"],
    position: "Outfielder / Pitcher",
    nationality: "American",
    race: null,
    yearsActive: "1914–1935",
    batHand: ["Left"],
    throwHand: ["Left"],
    awards: [
      "7× World Series Champion",
      "AL MVP (1923)",
      "MLB All-Century Team",
      "MLB All-Time Team",
    ],
    birthDay: "2/6/1895",
    deathDay: "8/16/1948",
    realName: "George Herman Ruth Jr.",
    nickNames: "The Bambino, The Sultan of Swat",
    yearInducted: 1936,
    commentOne: "One of the original five Hall of Fame inductees.",
    commentTwo:
      "Hit 714 home runs; transformed baseball into America's pastime.",
  },




  {
    firstName: "Nolan",
    lastName: "Ryan",
    teams: [
      "New York Mets",
      "California Angels",
      "Houston Astros",
      "Texas Rangers",
    ],
    primaryTeam: ["Texas Rangers"],
    position: "Pitcher",
    nationality: "American",
    race: null,
    yearsActive: "1966–1993",
    batHand: ["Right"],
    throwHand: ["Right"],
    awards: ["8× All-Star", "MLB Strikeout Leader", "7 No-Hitters"],
    birthDay: "1/31/1947",
    deathDay: null,
    realName: "Lynn Nolan Ryan Jr.",
    nickNames: "The Ryan Express",
    yearInducted: 1999,
    commentOne: "Holds the all-time strikeout record with 5,714.",
    commentTwo: "Pitched an MLB-record seven no-hitters.",
  },

  {
    firstName: "Ted",
    lastName: "Simmons",
    teams: ["St. Louis Cardinals", "Milwaukee Brewers", "Atlanta Braves"],
    primaryTeam: ["St. Louis Cardinals"],
    position: "Catcher",
    nationality: "American",
    race: null,
    yearsActive: "1968–1988",
    batHand: ["Switch"],
    throwHand: ["Right"],
    awards: ["8× All-Star", "Silver Slugger"],
    birthDay: "8/9/1949",
    deathDay: null,
    realName: "Ted Lyle Simmons",
    nickNames: "Simba",
    yearInducted: 2020,
    commentOne: "One of the best offensive catchers in MLB history.",
    commentTwo: "Inducted via Modern Baseball Era Committee.",
  },

  {
    firstName: "Ted",
    lastName: "Williams",
    teams: ["Boston Red Sox"],
    primaryTeam: ["Boston Red Sox"],
    position: "Left Fielder",
    nationality: "American",
    race: null,
    yearsActive: "1939–1960",
    batHand: ["Left"],
    throwHand: ["Right"],
    awards: [
      "2× AL MVP",
      "19× All-Star",
      "6× AL Batting Champion",
      "2× Triple Crown",
    ],
    birthDay: "8/30/1918",
    deathDay: "7/5/2002",
    realName: "Theodore Samuel Williams",
    nickNames: "The Splendid Splinter, Teddy Ballgame, The Kid",
    yearInducted: 1966,
    commentOne: "Last MLB player to hit over .400 in a season.",
    commentTwo: "Served in both WWII and the Korean War as a fighter pilot.",
  },
];
