export const hofMember = [
  {
    firstName: "Babe",
    lastName: "Ruth",
    teams: ["Boston Red Sox", "New York Yankees", "Boston Braves"],
    primaryTeam: ["New York Yankees"],
    position: "Outfielder / Pitcher",
    nationality: "United States",
    yearsActive: "1914–1935",
    batHand: ["Left"],
    throwHand: ["Left"],
    awards: [
      "7× World Series Champion",
      "AL MVP (1923)",
      "MLB All-Century Team",
      "MLB All-Time Team"
    ],
    birthDay: "2/6/1895",
    deathDay: "8/16/1948",
    realName: "George Herman Ruth Jr.",
    nickNames: "The Bambino, The Sultan of Swat",
    yearInducted: 1936,
    commentOne: "One of the original five Hall of Fame inductees.",
    commentTwo: "Hit 714 home runs; transformed baseball into America's pastime.",
  },
  {
    firstName: "Willie",
    lastName: "Mays",
    teams: ["New York Giants", "San Francisco Giants", "New York Mets"],
    primaryTeam: ["San Francisco Giants"],
    position: "Center Fielder",
    nationality: "United States",
    yearsActive: "1951–1973",
    batHand: ["Right"],
    throwHand: ["Right"],
    awards: ["24× All-Star", "2× NL MVP", "12× Gold Glove", "World Series Champion (1954)"],
    birthDay: "5/6/1931",
    deathDay: "6/18/2024",
    realName: "Willie Howard Mays Jr.",
    nickNames: "The Say Hey Kid",
    yearInducted: 1979,
    commentOne: "Arguably the most complete player in MLB history.",
    commentTwo: "Famous for his over-the-shoulder catch in the 1954 World Series.",
  },
  {
  firstName: "Ted",
  lastName: "Williams",
  teams: ["Boston Red Sox"],
  primaryTeam: ["Boston Red Sox"],
  position: "Left Fielder",
  nationality: "United States",
  yearsActive: "1939–1960",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "2× AL MVP",
    "19× All-Star",
    "6× AL Batting Champion",
    "2× Triple Crown"
  ],
  birthDay: "8/30/1918",
  deathDay: "7/5/2002",
  realName: "Theodore Samuel Williams",
  nickNames: "The Splendid Splinter, Teddy Ballgame, The Kid",
  yearInducted: 1966,
  commentOne: "Last MLB player to hit over .400 in a season (.406 in 1941).",
  commentTwo: "Served in both WWII and the Korean War as a fighter pilot.",
 },
 {
  firstName: "Ken",
  lastName: "Griffey Jr.",
  teams: ["Seattle Mariners", "Cincinnati Reds", "Chicago White Sox"],
  primaryTeam: ["Seattle Mariners"],
  position: "Center Fielder",
  nationality: "United States",
  yearsActive: "1989–2010",
  batHand: ["Left"],
  throwHand: ["Left"],
  awards: [
    "13× All-Star",
    "10× Gold Glove",
    "7× Silver Slugger",
    "1997 AL MVP"
  ],
  birthDay: "11/21/1969",
  deathDay: "Alive and Well",  realName: "George Kenneth Griffey Jr.",
  nickNames: "The Kid, Junior",
  yearInducted: 2016,
  commentOne: "One of the most iconic swings in baseball history.",
  commentTwo: "Hit 630 career home runs.",
 },
 {
  firstName: "Nolan",
  lastName: "Ryan",
  teams: ["New York Mets", "California Angels", "Houston Astros", "Texas Rangers"],
  primaryTeam: ["Texas Rangers"],
  position: "Pitcher",
  nationality: "United States",
  yearsActive: "1966–1993",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "8× All-Star",
    "MLB Strikeout Leader (all-time)",
    "MLB No-Hitter Record (7)"
  ],
  birthDay: "1/31/1947",
  deathDay: "Alive and Well",
  realName: "Lynn Nolan Ryan Jr.",
  nickNames: "The Ryan Express",
  yearInducted: 1999,
  commentOne: "Holds the all-time strikeout record with 5,714.",
  commentTwo: "Pitched an MLB-record seven no-hitters.",
 }
  // Add more players...
];