export const hofMember = [
{
  firstName: "Hank",
  lastName: "Aaron",
  teams: ["Milwaukee Braves", "Atlanta Braves", "Milwaukee Brewers"],
  primaryTeam: ["Atlanta Braves"],
  position: "Right Fielder",
  nationality: "American",
  race: "African American",
  yearsActive: "1954–1976",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "25× All-Star",
    "1957 NL MVP",
    "3× Gold Glove",
    "World Series Champion (1957)",
    "755 career home runs"
  ],
  birthDay: "2/5/1934",
  deathDay: "1/22/2021",
  realName: "Henry Louis Aaron",
  nickNames: "Hammerin' Hank",
  yearInducted: 1982,
  commentOne: "Broke Babe Ruth’s all-time home run record with 755.",
  commentTwo: "One of the greatest hitters and respected figures in baseball history.",
},

{
  firstName: "Grover Cleveland",
  lastName: "Alexander",
  teams: ["Philadelphia Phillies", "Chicago Cubs", "St. Louis Cardinals"],
  primaryTeam: ["Philadelphia Phillies"],
  position: "Pitcher",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1911–1930",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "3× Triple Crown",
    "6× NL Wins Leader",
    "6× NL ERA Leader",
    "World Series Champion (1926)"
  ],
  birthDay: "2/26/1887",
  deathDay: "11/4/1950",
  realName: "Grover Cleveland Alexander",
  nickNames: "Old Pete",
  yearInducted: 1938,
  commentOne: "One of the greatest pitchers in MLB history with 373 career wins.",
  commentTwo: "Pitched crucial relief in 1926 World Series Game 7 for Cardinals.",
},

{
  firstName: "Dick",
  lastName: "Allen",
  teams: ["Philadelphia Phillies", "Chicago White Sox", "St. Louis Cardinals", "Los Angeles Dodgers", "Oakland Athletics"],
  primaryTeam: ["Philadelphia Phillies"],
  position: "First Baseman / Third Baseman",
  nationality: "American",
  race: "African American",
  yearsActive: "1963–1977",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "7× All-Star",
    "1972 AL MVP",
    "1964 NL Rookie of the Year",
    "2× AL Home Run Leader"
  ],
  birthDay: "3/8/1942",
  deathDay: "12/7/2020",
  realName: "Richard Anthony Allen",
  nickNames: "Wampum Walloper, Crash",
  yearInducted: null,  // Not yet officially inducted but often discussed as deserving
  commentOne: "One of the most feared sluggers of the 1960s and 70s.",
  commentTwo: "Known for hitting towering home runs and his complex relationship with the press.",
},

{
  firstName: "Roberto",
  lastName: "Alomar Jr.",
  teams: ["San Diego Padres", "Toronto Blue Jays", "Baltimore Orioles", "Cleveland Indians", "New York Mets", "Chicago White Sox", "Arizona Diamondbacks"],
  primaryTeam: ["Toronto Blue Jays"],
  position: "Second Baseman",
  nationality: "Puerto Rican",
  race: "Latino",
  yearsActive: "1988–2004",
  batHand: ["Switch"],
  throwHand: ["Right"],
  awards: [
    "12× All-Star",
    "10× Gold Glove",
    "4× Silver Slugger",
    "2× World Series Champion (1992, 1993)",
    "1992 ALCS MVP"
  ],
  birthDay: "2/5/1968",
  deathDay: null,
  realName: "Roberto Alomar Velázquez",
  nickNames: "Robbie",
  yearInducted: 2011,
  commentOne: "One of the greatest second basemen in MLB history.",
  commentTwo: "Key figure in the Toronto Blue Jays' back-to-back championships.",
},

{
  firstName: "Walter",
  lastName: "Alston",
  teams: ["Brooklyn Dodgers", "Los Angeles Dodgers"],
  primaryTeam: ["Los Angeles Dodgers"],
  position: "Manager",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1954–1976 (Manager)",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "4× World Series Champion (1955, 1959, 1963, 1965)",
    "NL Manager of the Year (1955, 1959, 1963)"
  ],
  birthDay: "12/1/1911",
  deathDay: "10/1/1984",
  realName: "Walter Emmons Alston",
  nickNames: "Smokey",
  yearInducted: 1983,
  commentOne: "Managed the Dodgers for 23 seasons, winning four World Series titles.",
  commentTwo: "Known for his quiet leadership and one-game MLB playing career.",
},

{
  firstName: "Sparky",
  lastName: "Anderson",
  teams: ["Cincinnati Reds", "Detroit Tigers"],
  primaryTeam: ["Cincinnati Reds"],
  position: "Manager",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1970–1995 (Manager)",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "3× World Series Champion (1975, 1976, 1984)",
    "2× AL Manager of the Year (1984, 1987)"
  ],
  birthDay: "2/22/1934",
  deathDay: "11/4/2010",
  realName: "George Lee Anderson",
  nickNames: "Sparky",
  yearInducted: 2000,
  commentOne: "First manager to win World Series titles in both leagues (NL with Reds, AL with Tigers).",
  commentTwo: "Beloved figure in both Cincinnati and Detroit for leadership and character.",
},

{
  firstName: "Luis",
  lastName: "Aparicio",
  teams: ["Chicago White Sox", "Baltimore Orioles", "Boston Red Sox"],
  primaryTeam: ["Chicago White Sox"],
  position: "Shortstop",
  nationality: "Venezuelan",
  race: "Latino",
  yearsActive: "1956–1973",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "10× All-Star",
    "9× Gold Glove",
    "1956 AL Rookie of the Year",
    "AL Stolen Base Leader 9×"
  ],
  birthDay: "4/29/1934",
  deathDay: null,
  realName: "Luis Ernesto Aparicio Montiel",
  nickNames: "Little Louie",
  yearInducted: 1984,
  commentOne: "Revolutionized the shortstop position with speed and defense.",
  commentTwo: "First Venezuelan player inducted into the Baseball Hall of Fame.",
},

{
  firstName: "Luke",
  lastName: "Appling",
  teams: ["Chicago White Sox"],
  primaryTeam: ["Chicago White Sox"],
  position: "Shortstop",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1930–1950",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "7× All-Star",
    "2× AL Batting Champion (1936, 1943)"
  ],
  birthDay: "4/2/1907",
  deathDay: "1/3/1991",
  realName: "Lucius Benjamin Appling",
  nickNames: "Old Aches and Pains",
  yearInducted: 1964,
  commentOne: "Known for exceptional batting eye and consistency over two decades.",
  commentTwo: "Played 20 seasons with the White Sox and served in WWII.",
},

{
  firstName: "Richie",
  lastName: "Ashburn",
  teams: ["Philadelphia Phillies", "Chicago Cubs", "New York Mets"],
  primaryTeam: ["Philadelphia Phillies"],
  position: "Center Fielder",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1948–1962",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "6× All-Star",
    "2× NL Batting Champion"
  ],
  birthDay: "3/19/1927",
  deathDay: "9/9/1997",
  realName: "Donald Richard Ashburn",
  nickNames: "Whitey",
  yearInducted: 1995,
  commentOne: "Beloved Phillies player and later broadcaster.",
  commentTwo: "Key figure in the 1950 'Whiz Kids' NL Pennant team.",
},

{
  firstName: "Earl",
  lastName: "Averill",
  teams: ["Cleveland Indians", "Detroit Tigers", "Boston Braves"],
  primaryTeam: ["Cleveland Indians"],
  position: "Center Fielder",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1929–1941",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "6× All-Star"
  ],
  birthDay: "5/21/1902",
  deathDay: "8/16/1983",
  realName: "Howard Earl Averill",
  nickNames: "The Earl of Snohomish",
  yearInducted: 1975,
  commentOne: "One of the top hitters of the 1930s with consistent power and average.",
  commentTwo: "Played most of his career with the Cleveland Indians.",
},

{
  firstName: "Jeff",
  lastName: "Bagwell",
  teams: ["Houston Astros"],
  primaryTeam: ["Houston Astros"],
  position: "First Baseman",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1991–2005",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "1994 NL MVP",
    "1991 NL Rookie of the Year",
    "4× All-Star",
    "3× Silver Slugger",
    "Gold Glove (1994)"
  ],
  birthDay: "5/27/1968",
  deathDay: null,
  realName: "Jeffrey Robert Bagwell",
  nickNames: "Bags",
  yearInducted: 2017,
  commentOne: "One of the greatest players in Astros history with 449 home runs.",
  commentTwo: "Known for his unique batting stance and powerful offensive production.",
},

{
  firstName: "Harold",
  lastName: "Baines",
  teams: ["Chicago White Sox", "Baltimore Orioles", "Oakland Athletics", "Cleveland Indians", "Texas Rangers"],
  primaryTeam: ["Chicago White Sox"],
  position: "Right Fielder / Designated Hitter",
  nationality: "American",
  race: "African American",
  yearsActive: "1980–2001",
  batHand: ["Left"],
  throwHand: ["Left"],
  awards: [
    "6× All-Star",
    "Silver Slugger (1989)"
  ],
  birthDay: "3/15/1959",
  deathDay: null,
  realName: "Harold Douglas Baines",
  nickNames: null,
  yearInducted: 2019,
  commentOne: "A consistent hitter with 2,866 career hits and over 1,600 RBIs.",
  commentTwo: "Inducted via the Today's Game Era Committee for his long-standing contributions to the game.",
},

{
  firstName: "Frank",
  lastName: "Baker",
  teams: ["Philadelphia Athletics", "New York Yankees"],
  primaryTeam: ["Philadelphia Athletics"],
  position: "Third Baseman",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1908–1922",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "3× World Series Champion (1910, 1911, 1913)",
    "4× AL Home Run Leader"
  ],
  birthDay: "3/13/1886",
  deathDay: "6/28/1963",
  realName: "John Franklin Baker",
  nickNames: "Home Run Baker",
  yearInducted: 1955,
  commentOne: "Earned the nickname 'Home Run Baker' for his slugging prowess in the Deadball Era.",
  commentTwo: "Key player on Connie Mack’s powerhouse Athletics teams.",
},

{
  firstName: "Dave",
  lastName: "Bancroft",
  teams: ["Philadelphia Phillies", "New York Giants", "Boston Braves", "Brooklyn Robins"],
  primaryTeam: ["New York Giants"],
  position: "Shortstop",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1915–1930",
  batHand: ["Switch"],
  throwHand: ["Right"],
  awards: [
    "2× World Series Champion (1921, 1922)"
  ],
  birthDay: "4/20/1891",
  deathDay: "10/9/1972",
  realName: "David James Bancroft",
  nickNames: "Beauty",
  yearInducted: 1971,
  commentOne: "Known for outstanding defense and leadership at shortstop.",
  commentTwo: "Played key roles in John McGraw’s New York Giants championship teams.",
},

{
  firstName: "Ernie",
  lastName: "Banks",
  teams: ["Chicago Cubs"],
  primaryTeam: ["Chicago Cubs"],
  position: "Shortstop / First Baseman",
  nationality: "American",
  race: "African American",
  yearsActive: "1953–1971",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "14× All-Star",
    "2× NL MVP (1958, 1959)",
    "Gold Glove (1960)"
  ],
  birthDay: "1/31/1931",
  deathDay: "1/23/2015",
  realName: "Ernest Banks",
  nickNames: "Mr. Cub",
  yearInducted: 1977,
  commentOne: "One of the most beloved players in Cubs history with 512 home runs.",
  commentTwo: "Famous for his phrase: 'Let’s play two!' celebrating his love for the game.",
},

{
  firstName: "Al",
  lastName: "Barlick",
  teams: [],
  primaryTeam: [],
  position: "Umpire",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1940–1971 (National League Umpire)",
  batHand: [],
  throwHand: [],
  awards: [
    "7 World Series assignments",
    "7 All-Star Game assignments"
  ],
  birthDay: "4/2/1915",
  deathDay: "12/27/1995",
  realName: "Albert Joseph Barlick",
  nickNames: null,
  yearInducted: 1989,
  commentOne: "Respected National League umpire known for fairness and authority.",
  commentTwo: "Worked in MLB for over 30 years and influenced generations of umpires.",
},

{
  firstName: "Ed",
  lastName: "Barrow",
  teams: ["Boston Red Sox", "New York Yankees"],
  primaryTeam: ["New York Yankees"],
  position: "Executive / Manager",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1910s–1940s (Executive, Manager)",
  batHand: [],
  throwHand: [],
  awards: [
    "Oversaw Yankees' first great dynasty",
    "Credited with moving Babe Ruth to the outfield"
  ],
  birthDay: "5/10/1868",
  deathDay: "12/15/1953",
  realName: "Edward Grant Barrow",
  nickNames: null,
  yearInducted: 1953,
  commentOne: "As Yankees' general manager, built the foundation of the franchise’s dominance.",
  commentTwo: "Managed Red Sox to 1918 World Series before joining Yankees front office.",
},

{
  firstName: "Jake",
  lastName: "Beckley",
  teams: ["Pittsburgh Alleghenys", "Pittsburgh Pirates", "New York Giants", "Cincinnati Reds", "St. Louis Cardinals"],
  primaryTeam: ["Pittsburgh Pirates"],
  position: "First Baseman",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1888–1907",
  batHand: ["Left"],
  throwHand: ["Left"],
  awards: [],
  birthDay: "8/4/1867",
  deathDay: "6/25/1918",
  realName: "Jacob Peter Beckley",
  nickNames: "Eagle Eye",
  yearInducted: 1971,
  commentOne: "Collected over 2,900 career hits, ranking among 19th-century baseball’s top hitters.",
  commentTwo: "Remembered for consistency and longevity during baseball's early professional era.",
},

{
  firstName: "CoolPapa",
  lastName: "Bell",
  teams: ["St. Louis Stars", "Pittsburgh Crawfords", "Homestead Grays", "Kansas City Monarchs"],
  primaryTeam: ["Pittsburgh Crawfords"],
  position: "Center Fielder",
  nationality: "American",
  race: "African American",
  yearsActive: "1922–1946 (Negro Leagues)",
  batHand: ["Left"],
  throwHand: ["Left"],
  awards: [
    "Negro League World Series Champion",
    "Considered the fastest man ever to play professional baseball"
  ],
  birthDay: "5/17/1903",
  deathDay: "3/7/1991",
  realName: "James Thomas Bell",
  nickNames: "Cool Papa",
  yearInducted: 1974,
  commentOne: "Legendary speedster of the Negro Leagues; could round the bases in record time.",
  commentTwo: "Famous for the line: 'He was so fast he could turn off the light and be in bed before the room got dark.'",
},

{
  firstName: "Adrian",
  lastName: "Beltré",
  teams: ["Los Angeles Dodgers", "Seattle Mariners", "Boston Red Sox", "Texas Rangers"],
  primaryTeam: ["Texas Rangers"],
  position: "Third Baseman",
  nationality: "Dominican",
  race: "Latino",
  yearsActive: "1998–2018",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "4× All-Star",
    "5× Gold Glove",
    "4× Silver Slugger",
    "3,166 career hits"
  ],
  birthDay: "4/7/1979",
  deathDay: null,
  realName: "Adrián Beltré Pérez",
  nickNames: null,
  yearInducted: 2024,  // Scheduled for induction in 2024
  commentOne: "One of the greatest defensive and offensive third basemen in MLB history.",
  commentTwo: "Beloved for his playful personality and legendary career longevity.",
},

{
  firstName: "Johnny",
  lastName: "Bench",
  teams: ["Cincinnati Reds"],
  primaryTeam: ["Cincinnati Reds"],
  position: "Catcher",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1967–1983",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "14× All-Star",
    "2× NL MVP (1970, 1972)",
    "10× Gold Glove",
    "2× World Series Champion (1975, 1976)",
    "World Series MVP (1976)"
  ],
  birthDay: "12/7/1947",
  deathDay: null,
  realName: "Johnny Lee Bench",
  nickNames: null,
  yearInducted: 1989,
  commentOne: "Widely regarded as the greatest catcher in baseball history.",
  commentTwo: "Core member of Cincinnati's 'Big Red Machine' dynasty.",
},

{
  firstName: "Charles",
  lastName: "Bender",
  teams: ["Philadelphia Athletics", "Baltimore Terrapins", "Philadelphia Phillies"],
  primaryTeam: ["Philadelphia Athletics"],
  position: "Pitcher",
  nationality: "American",
  race: "Native American (Ojibwe)",
  yearsActive: "1903–1917",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "3× World Series Champion (1910, 1911, 1913)"
  ],
  birthDay: "5/5/1884",
  deathDay: "5/22/1954",
  realName: "Charles Albert Bender",
  nickNames: "Chief",
  yearInducted: 1953,
  commentOne: "One of the early great pitchers, known for intelligence and poise under pressure.",
  commentTwo: "First Native American star in Major League Baseball.",
},

{
  firstName: "Yogi",
  lastName: "Berra",
  teams: ["New York Yankees", "New York Mets"],
  primaryTeam: ["New York Yankees"],
  position: "Catcher",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1946–1965",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "18× All-Star",
    "3× AL MVP (1951, 1954, 1955)",
    "10× World Series Champion"
  ],
  birthDay: "5/12/1925",
  deathDay: "9/22/2015",
  realName: "Lawrence Peter Berra",
  nickNames: "Yogi",
  yearInducted: 1972,
  commentOne: "One of the most decorated champions in sports history.",
  commentTwo: "Famous for both his play and his timeless 'Yogi-isms' quotes.",
},

{
  firstName: "Craig",
  lastName: "Biggio",
  teams: ["Houston Astros"],
  primaryTeam: ["Houston Astros"],
  position: "Second Baseman / Catcher / Outfielder",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1988–2007",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "7× All-Star",
    "4× Gold Glove",
    "5× Silver Slugger",
    "3,060 career hits"
  ],
  birthDay: "12/14/1965",
  deathDay: null,
  realName: "Craig Alan Biggio",
  nickNames: null,
  yearInducted: 2015,
  commentOne: "One of the best all-around players of his era, all with the Astros.",
  commentTwo: "Known for versatility, hustle, and leadership.",
},

{
  firstName: "Bert",
  lastName: "Blyleven",
  teams: ["Minnesota Twins", "Texas Rangers", "Pittsburgh Pirates", "Cleveland Indians", "California Angels"],
  primaryTeam: ["Minnesota Twins"],
  position: "Pitcher",
  nationality: "Dutch-American",
  race: "Caucasian",
  yearsActive: "1970–1992",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "2× World Series Champion (1979, 1987)",
    "287 career wins",
    "3,701 strikeouts (5th all-time)"
  ],
  birthDay: "4/6/1951",
  deathDay: null,
  realName: "Rik Aalbert Blyleven",
  nickNames: "Bert",
  yearInducted: 2011,
  commentOne: "Renowned for his devastating curveball and longevity.",
  commentTwo: "Became a beloved broadcaster after his playing career.",
},

{
  firstName: "Wade",
  lastName: "Boggs",
  teams: ["Boston Red Sox", "New York Yankees", "Tampa Bay Devil Rays"],
  primaryTeam: ["Boston Red Sox"],
  position: "Third Baseman",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1982–1999",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "12× All-Star",
    "8× Silver Slugger",
    "2× Gold Glove",
    "1996 World Series Champion",
    "5× AL Batting Champion"
  ],
  birthDay: "6/15/1958",
  deathDay: null,
  realName: "Wade Anthony Boggs",
  nickNames: null,
  yearInducted: 2005,
  commentOne: "One of baseball's greatest contact hitters with 3,010 career hits.",
  commentTwo: "Known for his meticulous routine and legendary batting eye.",
},

{
  firstName: "Jim",
  lastName: "Bottomley",
  teams: ["St. Louis Cardinals", "Cincinnati Reds", "St. Louis Browns"],
  primaryTeam: ["St. Louis Cardinals"],
  position: "First Baseman",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1922–1937",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "1928 NL MVP",
    "World Series Champion (1926)"
  ],
  birthDay: "4/23/1900",
  deathDay: "12/11/1959",
  realName: "James Leroy Bottomley",
  nickNames: "Sunny Jim",
  yearInducted: 1974,
  commentOne: "Power-hitting first baseman known for his cheerful personality.",
  commentTwo: "Drove in over 1,400 runs with a career .310 batting average.",
},

{
  firstName: "Lou",
  lastName: "Boudreau",
  teams: ["Cleveland Indians", "Boston Red Sox"],
  primaryTeam: ["Cleveland Indians"],
  position: "Shortstop / Manager",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1938–1952",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "1948 AL MVP",
    "8× All-Star",
    "1948 World Series Champion"
  ],
  birthDay: "7/17/1917",
  deathDay: "8/10/2001",
  realName: "Louis Boudreau",
  nickNames: null,
  yearInducted: 1970,
  commentOne: "Player-manager who led the Indians to their last World Series title in 1948.",
  commentTwo: "Revolutionized infield positioning with defensive shifts.",
},

{
  firstName: "Roger",
  lastName: "Bresnahan",
  teams: ["Washington Senators", "Chicago Orphans", "Baltimore Orioles (NL)", "New York Giants", "St. Louis Cardinals"],
  primaryTeam: ["New York Giants"],
  position: "Catcher / Utility",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1897–1915",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [],
  birthDay: "6/11/1879",
  deathDay: "12/4/1944",
  realName: "Roger Philip Bresnahan",
  nickNames: "The Duke of Tralee",
  yearInducted: 1945,
  commentOne: "Pioneered the use of protective catcher’s gear including shin guards.",
  commentTwo: "Versatile athlete who played multiple positions in the early game.",
},

{
  firstName: "George",
  lastName: "Brett",
  teams: ["Kansas City Royals"],
  primaryTeam: ["Kansas City Royals"],
  position: "Third Baseman",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1973–1993",
  batHand: ["Left"],
  throwHand: ["Right"],
  awards: [
    "13× All-Star",
    "1980 AL MVP",
    "3× AL Batting Champion",
    "1985 World Series Champion",
    "Gold Glove"
  ],
  birthDay: "5/15/1953",
  deathDay: null,
  realName: "George Howard Brett",
  nickNames: null,
  yearInducted: 1999,
  commentOne: "One of the greatest third basemen of all time with over 3,000 hits.",
  commentTwo: "Iconic figure in Royals history and the famous 'Pine Tar Incident.'",
},

{
  firstName: "Lou",
  lastName: "Brock",
  teams: ["Chicago Cubs", "St. Louis Cardinals"],
  primaryTeam: ["St. Louis Cardinals"],
  position: "Left Fielder",
  nationality: "American",
  race: "African American",
  yearsActive: "1961–1979",
  batHand: ["Left"],
  throwHand: ["Left"],
  awards: [
    "6× All-Star",
    "2× World Series Champion (1964, 1967)",
    "Stolen Base Leader (8 times)"
  ],
  birthDay: "6/18/1939",
  deathDay: "9/6/2020",
  realName: "Louis Clark Brock",
  nickNames: null,
  yearInducted: 1985,
  commentOne: "One of the greatest base stealers in MLB history with 938 stolen bases.",
  commentTwo: "Played a key role in the Cardinals' championship teams of the 1960s.",
},

{
  firstName: "Dan",
  lastName: "Brouthers",
  teams: ["Buffalo Bisons", "Detroit Wolverines", "Boston Beaneaters", "Brooklyn Grooms", "Baltimore Orioles", "New York Giants"],
  primaryTeam: ["Buffalo Bisons"],
  position: "First Baseman",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1879–1904",
  batHand: ["Left"],
  throwHand: ["Left"],
  awards: [
    "5× Batting Champion"
  ],
  birthDay: "5/8/1858",
  deathDay: "8/2/1932",
  realName: "Dennis Joseph Brouthers",
  nickNames: "Big Dan",
  yearInducted: 1945,
  commentOne: "One of the most dominant hitters of the 19th century.",
  commentTwo: "Led the league in batting average and slugging multiple times.",
},

{
  firstName: "Mordecai",
  lastName: "Brown",
  teams: ["St. Louis Cardinals", "Chicago Cubs", "Cincinnati Reds", "Brooklyn Tip-Tops"],
  primaryTeam: ["Chicago Cubs"],
  position: "Pitcher",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1903–1916",
  batHand: ["Both"],
  throwHand: ["Right"],
  awards: [
    "2× World Series Champion (1907, 1908)"
  ],
  birthDay: "10/19/1876",
  deathDay: "2/14/1948",
  realName: "Mordecai Peter Centennial Brown",
  nickNames: "Three Finger",
  yearInducted: 1949,
  commentOne: "Hall of Fame pitcher known for his devastating curveball.",
  commentTwo: "Lost fingers in childhood accident, which helped create unique spin.",
},

{
  firstName: "Ray",
  lastName: "Brown",
  teams: ["Homestead Grays"],
  primaryTeam: ["Homestead Grays"],
  position: "Pitcher",
  nationality: "American",
  race: "African American",
  yearsActive: "1930s–1940s (Negro Leagues)",
  batHand: ["Both"],
  throwHand: ["Right"],
  awards: [
    "Negro World Series Champion",
    "Multiple All-Star selections"
  ],
  birthDay: "2/23/1908",
  deathDay: "2/8/1965",
  realName: "Raymond Brown",
  nickNames: null,
  yearInducted: 2006,
  commentOne: "Ace of the Homestead Grays during their dynasty years.",
  commentTwo: "Dominant pitcher in Negro League history with multiple no-hitters.",
},

{
  firstName: "Willard",
  lastName: "Brown",
  teams: ["Kansas City Monarchs", "St. Louis Browns"],
  primaryTeam: ["Kansas City Monarchs"],
  position: "Outfielder",
  nationality: "American",
  race: "African American",
  yearsActive: "1930s–1950s (Negro Leagues, MLB briefly)",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "Negro Leagues Champion",
    "One of the first Black players in American League history"
  ],
  birthDay: "6/26/1915",
  deathDay: "8/4/1996",
  realName: "Willard Jessie Brown",
  nickNames: "Home Run Brown",
  yearInducted: 2006,
  commentOne: "Power-hitting Negro Leagues star known for towering home runs.",
  commentTwo: "Briefly played in MLB before returning to Negro Leagues stardom.",
},

{
  firstName: "Morgan",
  lastName: "Bulkeley",
  teams: [],
  primaryTeam: [],
  position: "Executive / Administrator",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1882–1907 (Baseball Executive)",
  batHand: [],
  throwHand: [],
  awards: [],
  birthDay: "12/26/1837",
  deathDay: "11/6/1922",
  realName: "Morgan Gardner Bulkeley",
  nickNames: null,
  yearInducted: 1937,
  commentOne: "First president of the National League in 1876.",
  commentTwo: "Pioneering figure in baseball's organizational development.",
},
  
{
  firstName: "Jim",
  lastName: "Bunning",
  teams: ["Detroit Tigers", "Philadelphia Phillies", "Pittsburgh Pirates", "Los Angeles Dodgers"],
  primaryTeam: ["Philadelphia Phillies"],
  position: "Pitcher",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1955–1971",
  batHand: ["Right"],
  throwHand: ["Right"],
  awards: [
    "7× All-Star",
    "Perfect Game (1964)"
  ],
  birthDay: "10/23/1931",
  deathDay: "5/26/2017",
  realName: "James Paul David Bunning",
  nickNames: null,
  yearInducted: 1996,
  commentOne: "One of only a few pitchers to throw both a no-hitter and a perfect game.",
  commentTwo: "Later served as a U.S. Senator from Kentucky.",
},
  
{
  firstName: "Jesse",
  lastName: "Burkett",
  teams: ["Cleveland Spiders", "St. Louis Perfectos/Cardinals", "St. Louis Browns", "Boston Americans"],
  primaryTeam: ["Cleveland Spiders"],
  position: "Left Fielder",
  nationality: "American",
  race: "Caucasian",
  yearsActive: "1890–1905",
  batHand: ["Left"],
  throwHand: ["Left"],
  awards: [
    "3× Batting Champion"
  ],
  birthDay: "12/4/1868",
  deathDay: "5/27/1953",
  realName: "Jesse Clement Burkett",
  nickNames: "The Crab",
  yearInducted: 1946,
  commentOne: "Hit over .400 twice and finished with a .338 career average.",
  commentTwo: "Known for fiery competitiveness and superb hitting in the Deadball Era.",
},
  
  
  

























  {
    firstName: "Ken",
    lastName: "Griffey Jr.",
    teams: ["Seattle Mariners", "Cincinnati Reds", "Chicago White Sox"],
    primaryTeam: ["Seattle Mariners"],
    position: "Center Fielder",
    nationality: "American",
    race: "African American",
    yearsActive: "1989–2010",
    batHand: ["Left"],
    throwHand: ["Left"],
    awards: [
      "13× All-Star",
      "10× Gold Glove",
      "7× Silver Slugger",
      "1997 AL MVP",
    ],
    birthDay: "11/21/1969",
    deathDay: null,
    realName: "George Kenneth Griffey Jr.",
    nickNames: "The Kid, Junior",
    yearInducted: 2016,
    commentOne: "One of the most iconic swings in baseball history.",
    commentTwo: "Hit 630 career home runs.",
  },

  {
    firstName: "Ted",
    lastName: "Lyons",
    teams: ["Chicago White Sox"],
    primaryTeam: ["Chicago White Sox"],
    position: "Pitcher",
    nationality: "American",
    race: "Caucasian",
    yearsActive: "1923–1946",
    batHand: ["Right"],
    throwHand: ["Right"],
    awards: ["All-Star (1939)", "ERA leader 3×"],
    birthDay: "12/28/1900",
    deathDay: "7/25/1986",
    realName: "Theodore Amar Lyons",
    nickNames: "Sunday Teddy",
    yearInducted: 1955,
    commentOne: "Pitched his entire career for the White Sox.",
    commentTwo: "Won 260 games with a 3.67 ERA.",
  },
  
  {
    firstName: "Willie",
    lastName: "Mays",
    teams: ["New York Giants", "San Francisco Giants", "New York Mets"],
    primaryTeam: ["San Francisco Giants"],
    position: "Center Fielder",
    nationality: "American",
    race: "African American",
    yearsActive: "1951–1973",
    batHand: ["Right"],
    throwHand: ["Right"],
    awards: [
      "24× All-Star",
      "2× NL MVP",
      "12× Gold Glove",
      "World Series Champion (1954)",
    ],
    birthDay: "5/6/1931",
    deathDay: "6/18/2024",
    realName: "Willie Howard Mays Jr.",
    nickNames: "The Say Hey Kid",
    yearInducted: 1979,
    commentOne: "Arguably the most complete player in MLB history.",
    commentTwo:
      "Famous for his over-the-shoulder catch in the 1954 World Series.",
  },
  
  {
    firstName: "Babe",
    lastName: "Ruth",
    teams: ["Boston Red Sox", "New York Yankees", "Boston Braves"],
    primaryTeam: ["New York Yankees"],
    position: "Outfielder / Pitcher",
    nationality: "American",
    race: "Caucasian",
    yearsActive: "1914–1935",
    batHand: ["Left"],
    throwHand: ["Left"],
    awards: [
      "7× World Series Champion",
      "AL MVP (1923)",
      "MLB All-Century Team",
      "MLB All-Time Team",
    ],
    birthDay: "2/6/1895",
    deathDay: "8/16/1948",
    realName: "George Herman Ruth Jr.",
    nickNames: "The Bambino, The Sultan of Swat",
    yearInducted: 1936,
    commentOne: "One of the original five Hall of Fame inductees.",
    commentTwo:
      "Hit 714 home runs; transformed baseball into America's pastime.",
  },




  {
    firstName: "Nolan",
    lastName: "Ryan",
    teams: [
      "New York Mets",
      "California Angels",
      "Houston Astros",
      "Texas Rangers",
    ],
    primaryTeam: ["Texas Rangers"],
    position: "Pitcher",
    nationality: "American",
    race: "Caucasian",
    yearsActive: "1966–1993",
    batHand: ["Right"],
    throwHand: ["Right"],
    awards: ["8× All-Star", "MLB Strikeout Leader", "7 No-Hitters"],
    birthDay: "1/31/1947",
    deathDay: null,
    realName: "Lynn Nolan Ryan Jr.",
    nickNames: "The Ryan Express",
    yearInducted: 1999,
    commentOne: "Holds the all-time strikeout record with 5,714.",
    commentTwo: "Pitched an MLB-record seven no-hitters.",
  },

  {
    firstName: "Ted",
    lastName: "Simmons",
    teams: ["St. Louis Cardinals", "Milwaukee Brewers", "Atlanta Braves"],
    primaryTeam: ["St. Louis Cardinals"],
    position: "Catcher",
    nationality: "American",
    race: "Caucasian",
    yearsActive: "1968–1988",
    batHand: ["Switch"],
    throwHand: ["Right"],
    awards: ["8× All-Star", "Silver Slugger"],
    birthDay: "8/9/1949",
    deathDay: null,
    realName: "Ted Lyle Simmons",
    nickNames: "Simba",
    yearInducted: 2020,
    commentOne: "One of the best offensive catchers in MLB history.",
    commentTwo: "Inducted via Modern Baseball Era Committee.",
  },

  {
    firstName: "Ted",
    lastName: "Williams",
    teams: ["Boston Red Sox"],
    primaryTeam: ["Boston Red Sox"],
    position: "Left Fielder",
    nationality: "American",
    race: "Caucasian",
    yearsActive: "1939–1960",
    batHand: ["Left"],
    throwHand: ["Right"],
    awards: [
      "2× AL MVP",
      "19× All-Star",
      "6× AL Batting Champion",
      "2× Triple Crown",
    ],
    birthDay: "8/30/1918",
    deathDay: "7/5/2002",
    realName: "Theodore Samuel Williams",
    nickNames: "The Splendid Splinter, Teddy Ballgame, The Kid",
    yearInducted: 1966,
    commentOne: "Last MLB player to hit over .400 in a season.",
    commentTwo: "Served in both WWII and the Korean War as a fighter pilot.",
  },
];
